name: loop
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [main]

jobs:
  loop:
    name: loop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          pwd
          tree -a
        shell: bash
      - uses: ./
        with:
          debug: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
